[package]
name        = "expel"
version     = "0.0.1"
edition     = "2024"
description = """
An ESP32 (Xtensa) ELF Loader. It allows you to load and execute ELF binaries from your Rust-based ESP-HAL (no_std) firmware.
"""
authors     = [ "A31Nesta" ]
repository  = "https://git.black.observer/neos/expel"
license     = "MIT OR Apache-2.0"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
elf = { version = "0.8.0", default-features = false }
